In [4]:
import os
import pandas as pd

In [5]:
economy = pd.read_csv('./economy/national-gdp-wb.csv')
economy.merge(pd.read_csv('./economy/gdp-per-capita-worldbank.csv'), 'outer', on=['Entity', 'Year', 'Code']).drop('Code', axis=1)

,Entity,Year,"GDP, PPP (constant 2017 international $)","GDP per capita, PPP (constant 2017 international $)"
0,Afghanistan,2002,26890054000,1280.4631
1,Afghanistan,2003,29265058000,1292.3335
2,Afghanistan,2004,29678901000,1260.0605
3,Afghanistan,2005,33011757000,1352.3207
4,Afghanistan,2006,34780330000,1366.9932
...,...,...,...,...
6557,Zimbabwe,2018,36119544000,2399.6216
6558,Zimbabwe,2019,33832294000,2203.3967
6559,Zimbabwe,2020,31187640000,1990.3195
6560,Zimbabwe,2021,33828616000,2115.1445
6561,Zimbabwe,2022,36035043000,2207.9570